---
:concurrency: 4
:pidfile:  /var/www/vhosts/forgepost/shared/pids/sidekiq.pid
:logfile: /var/www/vhosts/forgepost/shared/log/sidekiq.log
:queues:
  - [critical, 4]
  - [high, 3]
  - [medium, 2]
  - [low, 1]